### ISSUE TITLE
vst3 not convolving

### ISSUE THREAD

**Issue by tremblap** [AlexHarker/HISSTools_Convolve#2]
with the latest version, on sequoia, on an m3, on reaper, the VST3 plug doesn't convolve. the through fader works. the vst2 and audiounit both work. but not the vst3.

**Comment by AlexHarker** [comment]
Do you know if the OS is relevant here? It seems unlikely, compared to hardware and repeat version, but if you know that it was working on a different OS for the same setup that would be helpful.

Do you also have any regression for vst3 on other setups? Do all GUI elements function as expected?

**Comment by tremblap** [comment]
As you know, I don't have any other machine... looking at my last backup, I was using on intel all 3 plug format in a random fashion and they behaved as far as I remember. sorry I can't help more. I've reloaded and it works in stereo - so it might be to do with when I declare it a 4 channel version - it is only affecting the vst3.

**Comment by AlexHarker** [comment]
OK - this might be an iplug2 channel issue then, although I can't quite figure out why you'd get dry sound - the extra info is definitely useful for the purpose of reproducing.

**Comment by tremblap** [comment]
to be more specific: I declared in Reaper's plugin routing a 4 channel plug on a 6 channel track.

**Comment by AlexHarker** [comment]
Sadly can't reproduce on REAPER v7.22 vst3 building from source on M3 Pro.

Can you please:

- screenshot the plugin when it is functioning incorrectly
- screenshot any relevant routing settings

These may help narrow down further. Thanks

**Comment by tremblap** [comment]
ok there is something strange with loading the plug in (vst3 only) for instance:

1. load the attached session, start playing, then solo another track - that new track doesn't convolve. stop and start, it now convolves...

2. instanciate a new version in the 6 channel track. go in the routing and declare the plug as 4x4 - it doesn't update. Save, and reload, and it is correct.

So there is something strange here. 
[test.RPP.zip](https://github.com/user-attachments/files/17634215/test.RPP.zip)

**Comment by tremblap** [comment]
ok it now works thanks
